version: '2'

services:
  multichanneltodo.front:
    image: phgache/multichanneltodofront:latest
    ports:
    - "5000:5001"
    environment:
      - DNX_apipath=${MULTICHANNELTODO_API_PATH}
      - DNX_env=${MULTICHANNELTODO_ENV}
      - "constraint:container!=~front*"
      - "constraint:node!=consul0"
    networks:
      - front

  lbfront:
    image: phgache/haproxy:latest
    ports:
      - "8080:80"
    environment:
      - "APP_NAME=multichanneltodofront"
      - "CONSUL_URL=consul0.westeurope.cloudapp.azure.com:8500"
      - "constraint:node==consul0"
    networks:
      - front

networks:
  front:
    driver: overlay
